### ISSUE TITLE
【Safari・PC・iPhone】ヘッダーのアニメーションが適用されていない

### ISSUE THREAD

**Issue by n-komatsu** [gizumo-inc/giztech-pro-lp#4]
safariで表示確認をしたところ、スクロールしてもヘッダーの背景が白にならない現象を確認しました。

原因を調査後、ご対応をお願いします！

```javascript
let scrollFromTop = $('html, body').scrollTop();
```
header.jsのchangeHeaderメソッド内のこの辺の記述が怪しいと思います...

キャプチャも添付します。

![スクリーンショット 2019-06-03 14 37 13](https://user-images.githubusercontent.com/44689317/58778405-68a74400-860d-11e9-8cf6-d72598fa5a05.png)

**Comment by n-komatsu** [comment]
当事象ですが、iPhone8のSafariでも確認しました。

**Comment by Takayyz** [comment]
【safari】PCおよびiPhoneで動作確認取れたのでクローズにします。
